config/routes.rb
Rails.application.routes.draw do

  get '/getting-started', to: 'steps#getting_started'
  get '/add-kaminari', to: 'steps#add-kaminari'
  get '/pagination-customize-views', to: 'steps#pagination-customize-views'
  get '/action-mailer', to: 'steps#action-mailer'
  get '/test-emails-with-letter-opener', to: 'steps#test-emails-with-letter-opener'
  get '/threading-with-suckerpunch', to: 'steps#threading-with-suckerpunch'
  get '/has-and-belongs-to-many', to: 'steps#has-and-belongs-to-many'
  get '/form-and-display', to: 'steps#form-and-display'
  get '/install-carrierwave', to: 'steps#install-carrierwave'
  get '/user-profile', to: 'steps#user-profile'
  get '/add-user-avatar-form', to: 'steps#add-user-avatar-form'
  get '/add-users-avatar', to: 'steps#add-users-avatar'
  get '/create-documents', to: 'steps#create-documents'
  get '/create-documentable-nested-form', to: 'steps#create-documentable-nested-form'
  get '/generate-thumbnails', to: 'steps#generate-thumbnails'
  get '/install-ActsAsTaggableOn', to: 'steps#install-ActsAsTaggableOn'
  get '/install-select2-rails', to: 'steps#install-select2-rails'
  get '/autocomplete-tags', to: 'steps#autocomplete-tags'
  get '/install-solr-with-sunspot', to: 'steps#install-solr-with-sunspot'
  get '/index-projects', to: 'steps#index-projects'
  get '/add-search-form', to: 'steps#add-search-form'
  get '/facet-status', to: 'steps#facet-status'
  get '/revamp-layout-with-sidebar', to: 'steps#revamp-layout-with-sidebar'
  get '/customize-pagination', to: 'steps#customize-pagination'
  get '/next-steps', to: 'steps#next_steps'

  root to: 'steps#overview'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/steps_controller.rb
class StepsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_header.html.erb
<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="/">Rails Intermediate 2</a>
    </div>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<ul class="nav nav-sidebar">
  <li class="<%= 'active' if current_page?('/') %>">
    <%= link_to 'Overview', root_path %>
  </li>
  <li class="<%= 'active' if current_page?('/getting-started') %>">
    <%= link_to 'Getting Started', getting_started_path %>
  </li>
</ul>

<ul class="nav nav-sidebar">
  <li class='disabled'>
    <a href="#" ><h4>Pagination</h4></a>
  </li>
  <li class="<%= 'active' if current_page?('/add-kaminari') %>">
    <%= link_to 'Add Kaminari', add_kaminari_path %>
  </li>
  <li class="<%= 'active' if current_page?('/pagination-customize-views') %>">
    <%= link_to 'Install Views & Customize', pagination_customize_views_path %>
  </li>
</ul>

<ul class="nav nav-sidebar">
  <li class='disabled'>
    <a href="#" ><h4>Email Notifications</h4></a>
  </li>
  <li class="<%= 'active' if current_page?('/action-mailer') %>">
    <%= link_to 'ActionMailer', action_mailer_path %>
  </li>
  <li class="<%= 'active' if current_page?('/test-emails-with-letter-opener') %>">
    <%= link_to 'Test emails with LetterOpener', '/test-emails-with-letter-opener' %>
  </li>
  <li class="<%= 'active' if current_page?('/threading-with-suckerpunch') %>">
    <%= link_to 'Threading with SuckerPunch', threading_with_suckerpunch_path %>
  </li>
</ul>


<ul class="nav nav-sidebar">
  <li class='disabled'>
    <a href="#" ><h4>Assign Users to Projects</h4></a>
  </li>
  <li class="<%= 'active' if current_page?('/has-and-belongs-to-many') %>">
    <%= link_to 'Has and Belongs to Many', '/has-and-belongs-to-many' %>
  </li>
  <li class="<%= 'active' if current_page?('/form-and-display') %>">
    <%= link_to 'Form & Display', '/form-and-display' %>
  </li>
</ul>

<ul class="nav nav-sidebar">
  <li class='disabled'>
    <a href="#" ><h4>Upload files</h4></a>
  </li>
  <li class="<%= 'active' if current_page?('/install-carrierwave') %>">
    <%= link_to 'Install Carrierwave', install_carrierwave_path %>
  </li>
  <li class="<%= 'active' if current_page?('/user-profile') %>">
    <%= link_to 'User Profile', '/user-profile' %>
  </li>
  <li class="<%= 'active' if current_page?('/add-user-avatar-form') %>">
    <%= link_to 'Add User Avatar Form', '/add-user-avatar-form' %>
  </li>
  <li class="<%= 'active' if current_page?('/generate-thumbnails') %>">
    <%= link_to 'Generate Thumbnails', generate_thumbnails_path %>
  </li>
<!--   <li class="<%= 'active' if current_page?('/create-documents') %>">
    <%= link_to 'Create Documents', create_documents_path %>
  </li>
  <li class="<%= 'active' if current_page?('/create-documentable-nested-form') %>">
    <%= link_to 'Create Documentable Nested Form', '/create-documentable-nested-form' %>
  </li> -->
</ul>

<ul class="nav nav-sidebar">
  <li class='disabled'>
    <a href="#" ><h4>Full-Text Search</h4></a>
  </li>
  <li class="<%= 'active' if current_page?('/install-solr-with-sunspot') %>">
    <%= link_to 'Install Solr with Sunspot', '/install-solr-with-sunspot' %>
  </li>
  <li class="<%= 'active' if current_page?('/index-projects') %>">
    <%= link_to 'Index Projects', '/index-projects' %>
  </li>
  <li class="<%= 'active' if current_page?('/add-search-form') %>">
    <%= link_to 'Add Search Form', '/add-search-form' %>
  </li>
  <li class="<%= 'active' if current_page?('/facet-status') %>">
    <%= link_to 'Facet Status', '/facet-status' %>
  </li>
</ul>

<ul class="nav nav-sidebar">
  <li class='disabled'>
    <a href="#" ><h4>Want more?</h4></a>
  </li>
  <li class='disabled'><%= link_to 'Facet Assignees', '' %></li>
  <li class='disabled'><%= link_to 'Add CKEditor WYSIWYG', '' %></li>
  <li class='disabled'><%= link_to 'Add tags with ActsAsTaggableOn', '' %></li>
  <li class='disabled'><%= link_to 'Install select2-rails gem to autocomplete tags', '' %></li>
  <li class='disabled'><%= link_to 'Customize Pagination with the Presenter pattern', '' %></li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rails Intermediate 2</title>

  <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">
  <link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">
  <link rel="stylesheet" type="text/css" href="http://bootswatch.com/flatly/bootstrap.min.css">
  <link rel="stylesheet" href="http://yandex.st/highlightjs/8.0/styles/monokai.min.css">
  <script src="http://yandex.st/highlightjs/8.0/highlight.min.js"></script>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/header' %>
  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-3 col-md-2 sidebar">
        <%= render 'layouts/navigation' %>
      </div>
      <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
        <%= yield %>
      </div>
    </div>
  </div>

</body>
</html>

app/views/steps/action-mailer.html.erb
<h1 class="page-header">ActionMailer</h1>

<blockquote>
  <p>Action Mailer allows you to send emails from your application using mailer classes and views. Mailers work very similarly to controllers. They inherit from ActionMailer::Base and live in app/mailers, and they have associated views that appear in app/views.</p>
</blockquote>

<h3>Goals</h3>
<blockquote>
  <ul>
    <li>Create a new ActionMailer class</li>
    <li>Create ActionMailer views</li>
    <li>Test our emails</li>
    <li>Delay delivery of email and send from new thread</li>
  </ul>
</blockquote>

<h3>Step 1</h3>
<blockquote>
  <p>Use the <code>mailer</code> generator to get going</p>
  <pre><code>rails g mailer Notifier notify_users</code></pre>
</blockquote>

<h3>Step 2</h3>
<blockquote>
  <p>Configure <code>Notifier</code> to send emails to all users</p>
  <pre><code>mail to: User.pluck(:email)</code></pre>
</blockquote>

<h3>Step 3</h3>
<blockquote>
  <p>Expect <code>comment</code>, <code>user</code> and <code>about</code> variables as parameters and revamp accordingly</p>
  <pre><code>  def notify_users comment, subject
  @comment = comment
  @subject = subject
  mail to: User.pluck(:email), subject: @subject
end</code></pre>
</blockquote>

<h3>Step 4</h3>
<blockquote>
  <p>Instantiate a new <code>mailer</code> instance on <code>comments#create</code></p>
  <pre><code>subject = "#{current_user.email} commented about Project: #{@project.title}"
Notifier.notify_users(@comment, subject).deliver</code></pre>
</blockquote>

app/views/steps/add-kaminari.html.erb
<h1 class="page-header">Add Kaminari</h1>

<blockquote>
  <p>Our project list is growing beyond reason! Add pagination to help users browse the list.</p>
</blockquote>

<h3>Step 1</h3>
<blockquote>
  <p>Add <code>kaminari</code> to your Gemfile</p>
  <pre><code>gem 'kaminari', github: 'amatsuda/kaminari'</code></pre>
</blockquote>

<h3>Step 2</h3>
<blockquote>
  <p>Run Bundler</p>
  <pre><code>bundle</code></pre>
</blockquote>

<h3>Step 3</h3>
<blockquote>
  <p>Add <code>.page(params[:page])</code> to your <code>projects#index</code> controller action.</p>
  <pre><code>def index
  @projects = Project.order(sort_column => sort_direction).page(params[:page]).per(10)
end</code></pre>
</blockquote>

<h3>Step 4</h3>
<blockquote>
  <p>Add <code>pagination_tag</code> helper method to your <code>projects#index</code> view.</p>
  <pre><code>&lt;%= paginate @projects %&gt;</code></pre>
</blockquote>

app/views/steps/autocomplete-tags.html.erb
<h1 class="page-header">Autocomplete Tags</h1>

<h3>TO DO</h3>

app/views/steps/create-documentable-nested-form.html.erb
<h1 class="page-header">Create Documentable Nested Forms</h1>


<h3>Step 1</h3>
<blockquote>
  <p></p>
  <pre><code>accepts_nested_attributes_for :documents_attributes</code></pre>
</blockquote>

<h3>Step 1</h3>
<blockquote>
  <p></p>
  <pre><code></code></pre>
</blockquote>

<h3>Step 1</h3>
<blockquote>
  <p></p>
  <pre><code></code></pre>
</blockquote>

<h3>Step 1</h3>
<blockquote>
  <p></p>
  <pre><code></code></pre>
</blockquote>

<h3>Step 1</h3>
<blockquote>
  <p></p>
  <pre><code></code></pre>
</blockquote>

app/views/steps/create-documents.html.erb
<h1 class="page-header">Create Documents</h1>

<blockquote>
  <p></p>
</blockquote>

<h3>Step 1</h3>
<blockquote>
  <p></p>
  <pre><code>rails g model document data:string documentable:references{polymorphic}</code></pre>
</blockquote>

<h3>Step 2</h3>
<blockquote>
  <p></p>
  <pre><code>rake db:migrate</code></pre>
</blockquote>

<h3>Step 3</h3>
<blockquote>
  <p></p>
  <pre><code>has_many :documents, as: :documentable</code></pre>
</blockquote>

<h3>Step 4</h3>
<blockquote>
  <p></p>
  <pre><code>mount_uploader :data, DocumentUploader</code></pre>
</blockquote>

app/views/steps/facet-status.html.erb
<h1 class="page-header">Facet Tags</h1>

<h3>Step 1</h3>
<blockquote>
  <p>Change <code>container</code> class to <code>container-fluid</code> in <code>layouts/application</code> and <code>layouts/_header</code></p>
</blockquote>

<h3>Step 2</h3>
<blockquote>
  <p>Add <code>status</code> facet to search block</p>
  <pre><code>facet :status
with(:status, params[:status]) if params[:status].present?</code></pre>
</blockquote>

<h3>Step 3</h3>
<blockquote>
  <p>Split <code>search</code> view to have a sidebar and add status facet panel.</p>
  <pre><code>&lt;div class="panel panel-default"&gt;
  &lt;div class="panel-heading"&gt;Status&lt;/div&gt;
  &lt;ul class="list-group"&gt;
    &lt;% @search.facet(:status).rows.each do |facet| %&gt;
      &lt;li class="list-group-item"&gt;
        &lt;span class="badge"&gt;&lt;%= facet.count %&gt;&lt;/span&gt;
        &lt;%= link_to project_status_label(facet.value), params.merge(status: facet.value) %&gt;
      &lt;/li&gt;
    &lt;% end -%&gt;
  &lt;/ul&gt;
&lt;/div&gt;</code></pre>
</blockquote>

<h3>Step 4</h3>
<blockquote>
  <p>Add a link to reset the status selection.</p>
  <pre><code>&lt;%= link_to icon_tag('refresh'), params.except(:status), class: 'pull-right' %&gt;</code></pre>
</blockquote>

<h3>Step 5</h3>
<blockquote>
  <p>Persist status selection on new searches.</p>
  <pre><code>&lt;%= f.input :status, as: :hidden, input_html: {name: :status, value: params[:status]} %&gt;</code></pre>
</blockquote>

app/views/steps/has-and-belongs-to-many.html.erb
<h1 class="page-header">Has and Belongs to Many</h1>
<blockquote>
  <p>A <code>has_and_belongs_to_many</code> association creates a direct many-to-many connection with another model, with no intervening model.</p>
  <p>Specifies a many-to-many relationship with another class. This associates two classes via an intermediate join table. Unless the join table is explicitly specified as an option, it is guessed using the lexical order of the class names. So a join between Developer and Project will give the default join table name of “developers_projects” because “D” precedes “P” alphabetically.</p>
  <p><%= image_tag 'habtm.png', alt: '' %></p>
  <p>There is another way of defining many-to-many association and that is <code>has_many :through</code></p>
  <p>A <code>has_many :through</code> association is often used to set up a many-to-many connection with another model. This association indicates that the declaring model can be matched with zero or more instances of another model by proceeding through a third model.</p>
  <p><%= image_tag 'has_many_through.png', alt: '' %></p>
</blockquote>

<h3>Goals</h3>
<blockquote>
  <p>Turns out not everyone wants to get notified of new comments.</p>
  <p>While we don't want to let the user decide, we can surely send emails only to the users assigned to the project.</p>
  <ul>
    <li>Create a migration for a users to projects many to many relationship</li>
    <li>Add user assignment to project form</li>
    <li>Send an email only to those who are assigned to the project</li>
  </ul>
</blockquote>

<h3>Step 1</h3>
<blockquote>
  <p>Use the <code>migration</code> generator to create a new migration for our many-to-many relationship</p>
  <pre><code>rails g migration CreateProjectsUsers user:references project:references</code></pre>
</blockquote>

<h3>Step 2</h3>
<blockquote>
  <p>Remove <code>id</code> primary key on our association table</p>
  <pre><code>create_table :projects_users, id: false do |t|</code></pre>
</blockquote>

<h3>Step 3</h3>
<blockquote>
  <p>Run the migration</p>
  <pre><code>rake db:migrate</code></pre>
</blockquote>

<h3>Step 4</h3>
<blockquote>
  <p>Association users and projects</p>
  <p>In <code>app/models/user.rb</code></p>
  <pre><code>has_and_belongs_to_many :projects</code></pre>
  <p>In <code>app/models/project.rb</code></p>
  <pre><code>has_and_belongs_to_many :users</code></pre>
</blockquote>

<h3>Step 5</h3>
<blockquote>
  <p>Test in console</p>
  <pre><code>$ rails c
project = Project.first
project.users << User.first
</code></pre>
</blockquote>

app/views/steps/html-email-template.html.erb
<h1 class="page-header">HTML Email Template</h1>

<h3>TO DO</h3>

app/views/steps/install-ActsAsTaggableOn.html.erb
<h1 class="page-header">Install ActsAsTaggableOn</h1>

<h3>TO DO</h3>

app/views/steps/install-select2-rails.html.erb
<h1 class="page-header">Install Select2 for Rails</h1>

<h3>TO DO</h3>

app/views/steps/overview.html.erb
<h1 class="page-header">Rails Intermediate Part 2</h1>
<blockquote>
  <p>
    In this lesson, we will have a look at some of the features that makes Rails good at developping prototypes fast.
  </p>
  <p>
    We will go over a few of the most common tools found in Rails applications.
  </p>
  <p>
    Additionally, we will apply our learnings to our previously created Project Management System called Milo.
  </p>
</blockquote>

<h2>Goals</h2>
<blockquote>
  <ul>
    <li>Add pagination with Kaminari</li>
    <li>Assign users to projects</li>
    <li>Send email notifications asynchronously</li>
    <li>Add user profiles with avatars</li>
    <li>Upload files with Carrierwave</li>
    <li>Add autocompleted tags to project</li>
    <li>Add full-text search with Solr & Sunspot</li>
  </ul>
</blockquote>

<h2>Meta Goals</h2>
<blockquote>
  <p>When you have completed today's goals you should understand:</p>
  <ul>
    <li>Presenter Pattern</li>
    <li>Threading</li>
    <li>ActionMailer</li>
    <li>Indexing & Faceting</li>
  </ul>
</blockquote>

<h2>Requirements</h2>
<blockquote>
  <p>
    We're going to be working with:
  </p>

  <ul>
    <li>Ruby 2.1.1</li>
    <li>Rails 4.1.x</li>
    <li>Bundler</li>
    <li>sqlite</li>
    <li>Terminal</li>
    <li>Sublime Text</li>
  </ul>
</blockquote>

app/views/steps/pagination-customize-views.html.erb
<h1 class="page-header">Customize Views</h1>

<blockquote>
  <p>Could look a little prettier than that.</p>
  <p><%= image_tag 'pagination.png', alt: '' %></p>
</blockquote>

<h3>Goals</h3>
<blockquote>
  <p>Revamp pagination to get a different look.</p>
  <p><%= image_tag 'pagination_3.png', alt: '' %></p>
</blockquote>

<h3>Step 1</h3>
<blockquote>
  <p>Import views from <code>kaminari</code></p>
  <pre><code>rails g kaminari:views bootstrap</code></pre>
</blockquote>

<h3>Step 2</h3>
<blockquote>
  <p>Fix <code>paginator</code> partial to fit Twitter Bootstrap 3 requirements.</p>
  <p>Move the <code>pagination</code> class to <code>ul</code></p>
  <pre><code>&lt;ul class='pagination'&gt;...&lt;/ul&gt;</code></pre>
</blockquote>

<h3>Step 3</h3>
<blockquote>
  <p>Add pagination total count and other useful information under the main title.</p>
  <pre><code>&lt;p&gt;&lt;%= page_entries_info @projects %&gt;&lt;/p&gt;</code></pre>
</blockquote>

app/views/steps/revamp-layout-with-sidebar.html.erb
<h1 class="page-header">Revamp Layout with Sidebar</h1>

<h3>TO DO</h3>

app/views/steps/user-profile.html.erb
<h1 class="page-header">User Profiles</h1>
<blockquote>
  <p>Let everyone chose their own avatar.</p>
  <p>Once a user is logged in, he has access to a profile view where he can edit his details and his avatar.</p>
</blockquote>

<h3>Step 1</h3>
<blockquote>
  <p>Add UsersController with a <code>profile</code> action</p>
  <pre><code>rails g controller users profile</code></pre>
</blockquote>

<h3>Step 2</h3>
<blockquote>
  <p>Fix route</p>
  <pre><code>get '/profile', to: 'users#profile'</code></pre>
</blockquote>

<h3>Step 3</h3>
<blockquote>
  <p>Add link to profile in header navigation</p>
  <pre><code>&lt;li&gt;&lt;%= link_to icon_tag('user fa-2x'), profile_path %&gt;&lt;/li&gt;</code></pre>
</blockquote>

<h3>Step 4</h3>
<blockquote>
  <p>Deny users that are not logged in.</p>
  <pre><code>raise ActionController::RoutingError.new('Not Found') unless user_signed_in?</code></pre>
</blockquote>

<h3>Step 5</h3>
<blockquote>
  <p>Instantiate <code>@projects</code> with current_user's projects</p>
  <pre><code>@projects = current_user.projects</code></pre>
</blockquote>

<h3>Step 6</h3>
<blockquote>
  <p>Add view</p>
  <pre><code>&lt;h1 class="page-header"&gt;&lt;%= current_user.email %&gt;'s Profile&lt;/h1&gt;

&lt;h3&gt;Currently working on&lt;/h3&gt;

&lt;ul class="list-group"&gt;
  &lt;% @projects.each do |p| %&gt;
    &lt;li class="list-group-item"&gt;
      &lt;span class="pull-right"&gt;&lt;%= project_status_label(p.status) %&gt;&lt;/span&gt;
      &lt;%= link_to p.title, p %&gt;
    &lt;/li&gt;
  &lt;% end %&gt;
&lt;/ul&gt;</code></pre>
</blockquote>